In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Time Series

## Live Demos

In [3]:
bike_sharing_data = pd.read_csv("data/bike-sharing-demand/train.csv")

In [4]:
bike_sharing_data

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [5]:
bike_sharing_data.dtypes

datetime       object
season          int64
holiday         int64
workingday      int64
weather         int64
temp          float64
atemp         float64
humidity        int64
windspeed     float64
casual          int64
registered      int64
count           int64
dtype: object

In [6]:
bike_sharing_data.datetime = pd.to_datetime(bike_sharing_data.datetime)

In [7]:
bike_sharing_data = bike_sharing_data.set_index("datetime")

In [8]:
categorical_feature_names = ["season", "holiday", "workingday", "weather"]
categorical_features = pd.get_dummies(bike_sharing_data[categorical_feature_names].astype(str), drop_first = True)
bike_sharing_data = bike_sharing_data.merge(categorical_features, left_index = True, right_index = True)
bike_sharing_data = bike_sharing_data.drop(columns = categorical_feature_names)

In [9]:
bike_sharing_data

,temp,atemp,humidity,windspeed,casual,registered,count,season_2,season_3,season_4,holiday_1,workingday_1,weather_2,weather_3,weather_4
datetime,,,,,,,,,,,,,,,
2011-01-01 00:00:00,9.84,14.395,81,0.0000,3,13,16,0,0,0,0,0,0,0,0
2011-01-01 01:00:00,9.02,13.635,80,0.0000,8,32,40,0,0,0,0,0,0,0,0
2011-01-01 02:00:00,9.02,13.635,80,0.0000,5,27,32,0,0,0,0,0,0,0,0
2011-01-01 03:00:00,9.84,14.395,75,0.0000,3,10,13,0,0,0,0,0,0,0,0
2011-01-01 04:00:00,9.84,14.395,75,0.0000,0,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-12-19 19:00:00,15.58,19.695,50,26.0027,7,329,336,0,0,1,0,1,0,0,0
2012-12-19 20:00:00,14.76,17.425,57,15.0013,10,231,241,0,0,1,0,1,0,0,0
2012-12-19 21:00:00,13.94,15.910,61,15.0013,4,164,168,0,0,1,0,1,0,0,0
2012-12-19 22:00:00,13.94,17.425,61,6.0032,12,117,129,0,0,1,0,1,0,0,0
2012-12-19 23:00:00,13.12,16.665,66,8.9981,4,84,88,0,0,1,0,1,0,0,0

In [10]:
bike_sharing_data.describe().T

,count,mean,std,min,25%,50%,75%,max
temp,10886.0,20.230860,7.791590,0.82,13.9400,20.500,26.2400,41.0000
atemp,10886.0,23.655084,8.474601,0.76,16.6650,24.240,31.0600,45.4550
humidity,10886.0,61.886460,19.245033,0.00,47.0000,62.000,77.0000,100.0000
windspeed,10886.0,12.799395,8.164537,0.00,7.0015,12.998,16.9979,56.9969
casual,10886.0,36.021955,49.960477,0.00,4.0000,17.000,49.0000,367.0000
registered,10886.0,155.552177,151.039033,0.00,36.0000,118.000,222.0000,886.0000
count,10886.0,191.574132,181.144454,1.00,42.0000,145.000,284.0000,977.0000
season_2,10886.0,0.251056,0.433641,0.00,0.0000,0.000,1.0000,1.0000
season_3,10886.0,0.251056,0.433641,0.00,0.0000,0.000,1.0000,1.0000
season_4,10886.0,0.251148,0.433694,0.00,0.0000,0.000,1.0000,1.0000
holiday_1,10886.0,0.028569,0.166599,0.00,0.0000,0.000,0.0000,1.0000
workingday_1,10886.0,0.680875,0.466159,0.00,0.0000,1.000,1.0000,1.0000
weather_2,10886.0,0.260334,0.438837,0.00,0.0000,0.000,1.0000,1.0000
weather_3,10886.0,0.078909,0.269609,0.00,0.0000,0.000,0.0000,1.0000
weather_4,10886.0,0.000092,0.009584,0.00,0.0000,0.000,0.0000,1.0000

In [11]:
bike_sharing_attributes, bike_sharing_target = bike_sharing_data.drop(columns = ["casual", "registered", "count"]), bike_sharing_data["count"]

In [12]:
model = LinearRegression()

In [13]:
model.fit(bike_sharing_attributes, bike_sharing_target)

LinearRegression()

In [14]:
model.score(bike_sharing_attributes, bike_sharing_target)

0.2767549620228168

In [15]:
predictions = model.predict(bike_sharing_attributes)

In [16]:
predictions

array([ 13.10928117,   7.16917332,   7.16917332, ..., 178.11332088,
       176.95943452, 155.94285748])

In [17]:
np.sqrt(mean_squared_error(bike_sharing_target, predictions))

154.04507737677713